"""
Seeded data fixtures, user personas, baseline profiles, canonical test scenarios,
and comprehensive dataset of regular payees with regular amounts, times, and frequencies.
"""
import json
import datetime
from typing import Dict, List, Any

REGULAR_PAYEES_DATASET: List[Dict[str, Any]] = [
    {
        "id": "R201",
        "name": "Suresh Nair (Landlord)",
        "upi": "suresh.nair@okhdfcbank",
        "avatar_initials": "SN",
        "avatar_color": "#EBD5FF",
        "regular_amount": 50000.0,
        "regular_time": "10:00 AM – 12:00 PM (1st–5th of Month)",
        "frequency": "Monthly",
        "category": "Rent / Housing",
        "tx_count": 14,
        "is_regular": True,
        "verified_on": "Paytm Bank"
    },
    {
        "id": "R202",
        "name": "Nature Basket Groceries",
        "upi": "naturebasket@paytm",
        "avatar_initials": "NB",
        "avatar_color": "#D1FAE5",
        "regular_amount": 850.0,
        "regular_time": "11:00 AM – 8:00 PM (Weekly)",
        "frequency": "Weekly",
        "category": "Groceries / Daily Needs",
        "tx_count": 28,
        "is_regular": True,
        "verified_on": "Paytm"
    },
    {
        "id": "R203",
        "name": "Sujata Banerjee",
        "upi": "sujata.b@phonepe",
        "avatar_initials": "SB",
        "avatar_color": "#EBD5FF",
        "regular_amount": 2500.0,
        "regular_time": "2:00 PM – 7:00 PM",
        "frequency": "Bi-weekly",
        "category": "Family & Friends",
        "tx_count": 19,
        "is_regular": True,
        "verified_on": "PhonePe"
    },
    {
        "id": "R204",
        "name": "Adani Electricity Board",
        "upi": "adanipower@billpay",
        "avatar_initials": "AE",
        "avatar_color": "#FEF3C7",
        "regular_amount": 1850.0,
        "regular_time": "9:00 AM – 5:00 PM (Monthly)",
        "frequency": "Monthly",
        "category": "Utility Bill",
        "tx_count": 12,
        "is_regular": True,
        "verified_on": "Paytm BillPay"
    },
    {
        "id": "R205",
        "name": "Airtel Fiber Broadband",
        "upi": "airtelwifi@paytm",
        "avatar_initials": "AF",
        "avatar_color": "#FEE2E2",
        "regular_amount": 1199.0,
        "regular_time": "10:00 AM – 4:00 PM (Monthly)",
        "frequency": "Monthly",
        "category": "Broadband / WiFi",
        "tx_count": 11,
        "is_regular": True,
        "verified_on": "Paytm"
    },
    {
        "id": "R991",
        "name": "Amit Kumar",
        "upi": "amit.kumar89@okaxis",
        "avatar_initials": "AK",
        "avatar_color": "#E2E8F0",
        "regular_amount": 0.0,
        "regular_time": "Unknown / First Time",
        "frequency": "One-time (New)",
        "category": "Personal Transfer",
        "tx_count": 0,
        "is_regular": False,
        "verified_on": "Axis Bank"
    },
    {
        "id": "R999",
        "name": "QuickCrypto Pay",
        "upi": "fastcrypto@ybl",
        "avatar_initials": "QC",
        "avatar_color": "#FFE4E6",
        "regular_amount": 0.0,
        "regular_time": "Unusual Deep Night (3:18 AM)",
        "frequency": "One-time (New)",
        "category": "Investment / Digital Asset",
        "tx_count": 0,
        "is_regular": False,
        "verified_on": "Yes Bank"
    }
]

PERSONAS = {
    "U101": {
        "user_id": "U101",
        "name": "Priya Sharma",
        "persona": "Student",
        "upi_handle": "priya.sharma@paytm",
        "median_amount": 350.0,
        "mad_amount": 180.0,
        "p90_amount": 900.0,
        "p95_amount": 1400.0,
        "max_amount": 100000.0,
        "usual_start_hour": 8,
        "usual_end_hour": 23,
        "known_recipients": [
            {"id": "R101", "name": "Hostel Canteen", "upi": "canteen@upi", "tx_count": 42, "regular_amount": 120.0, "regular_time": "12:00 PM – 8:00 PM"},
            {"id": "R102", "name": "Campus Bookstore", "upi": "books@upi", "tx_count": 8, "regular_amount": 450.0, "regular_time": "2:00 PM – 5:00 PM"},
            {"id": "R103", "name": "Sneha (Roommate)", "upi": "sneha@okhdfc", "tx_count": 19, "regular_amount": 300.0, "regular_time": "Anytime"},
            {"id": "R104", "name": "Zomato Delivery", "upi": "zomato@icici", "tx_count": 31, "regular_amount": 280.0, "regular_time": "7:00 PM – 10:00 PM"},
        ],
        "known_devices": ["DEV_PRIYA_PIXEL7"],
        "usual_regions": ["Bengaluru"],
        "transaction_count": 100,
        "profile_status": "ESTABLISHED",
        "trusted_patterns": [
            {"title": "Mobile Recharge", "category": "Utilities", "typical_amount": 299.0, "frequency": "Monthly", "recipient_id": "R104"},
            {"title": "Hostel Mess Fee", "category": "Education", "typical_amount": 2500.0, "frequency": "Monthly", "recipient_id": "R101"},
        ]
    },
    "U102": {
        "user_id": "U102",
        "name": "Vikram Verma",
        "persona": "Salaried Professional",
        "upi_handle": "vikram.verma@paytm",
        "median_amount": 1250.0,
        "mad_amount": 600.0,
        "p90_amount": 4500.0,
        "p95_amount": 8000.0,
        "max_amount": 100000.0, # Max transfer limit set to 1 Lakh (100,000)
        "usual_start_hour": 8,
        "usual_end_hour": 22,
        "known_recipients": [
            {"id": "R201", "name": "Suresh Nair (Landlord)", "upi": "suresh.nair@okhdfcbank", "tx_count": 14, "regular_amount": 50000.0, "regular_time": "10:00 AM – 12:00 PM (1st–5th)"},
            {"id": "R202", "name": "Nature Basket Groceries", "upi": "naturebasket@paytm", "tx_count": 28, "regular_amount": 850.0, "regular_time": "11:00 AM – 8:00 PM"},
            {"id": "R203", "name": "Sujata Banerjee", "upi": "sujata.b@phonepe", "tx_count": 19, "regular_amount": 2500.0, "regular_time": "2:00 PM – 7:00 PM"},
            {"id": "R204", "name": "Adani Electricity", "upi": "adanipower@billpay", "tx_count": 12, "regular_amount": 1850.0, "regular_time": "9:00 AM – 5:00 PM"},
            {"id": "R205", "name": "Airtel Fiber", "upi": "airtelwifi@paytm", "tx_count": 11, "regular_amount": 1199.0, "regular_time": "10:00 AM – 4:00 PM"},
        ],
        "known_devices": ["DEV_VIKRAM_IPHONE15"],
        "usual_regions": ["Mumbai", "Pune"],
        "transaction_count": 140,
        "profile_status": "ESTABLISHED",
        "trusted_patterns": [
            {"title": "House Rent", "category": "Rent/Housing", "typical_amount": 50000.0, "frequency": "Monthly (1st-5th)", "recipient_id": "R201"},
            {"title": "Airtel Broadband", "category": "Utilities", "typical_amount": 1199.0, "frequency": "Monthly", "recipient_id": "R205"},
            {"title": "Electricity Bill", "category": "Utilities", "typical_amount": 1850.0, "frequency": "Monthly", "recipient_id": "R204"},
        ]
    },
    "U103": {
        "user_id": "U103",
        "name": "Ramesh Patel",
        "persona": "Shopkeeper / Merchant",
        "upi_handle": "patel.stores@paytm",
        "median_amount": 6500.0,
        "mad_amount": 3200.0,
        "p90_amount": 18000.0,
        "p95_amount": 25000.0,
        "max_amount": 100000.0,
        "usual_start_hour": 9,
        "usual_end_hour": 21,
        "known_recipients": [
            {"id": "R301", "name": "Gujarat Agro Wholesalers", "upi": "gujaratagro@icici", "tx_count": 35, "regular_amount": 22000.0, "regular_time": "10:00 AM – 2:00 PM"},
            {"id": "R302", "name": "Apex Packaging Mart", "upi": "apexpack@sbi", "tx_count": 18, "regular_amount": 5400.0, "regular_time": "12:00 PM – 4:00 PM"},
            {"id": "R303", "name": "Local Transport Logistics", "upi": "transport@kotak", "tx_count": 22, "regular_amount": 3200.0, "regular_time": "11:00 AM – 5:00 PM"},
        ],
        "known_devices": ["DEV_RAMESH_SAMSUNG_S23"],
        "usual_regions": ["Ahmedabad"],
        "transaction_count": 175,
        "profile_status": "ESTABLISHED",
        "trusted_patterns": [
            {"title": "Wholesale Inventory", "category": "Business Supplies", "typical_amount": 22000.0, "frequency": "Bi-weekly", "recipient_id": "R301"},
            {"title": "Commercial Space Rent", "category": "Rent/Housing", "typical_amount": 18000.0, "frequency": "Monthly", "recipient_id": "R302"},
        ]
    },
    "U104": {
        "user_id": "U104",
        "name": "Ananya Rao",
        "persona": "Freelancer / Consultant",
        "upi_handle": "ananya.design@paytm",
        "median_amount": 4200.0,
        "mad_amount": 2100.0,
        "p90_amount": 22000.0,
        "p95_amount": 38000.0,
        "max_amount": 100000.0,
        "usual_start_hour": 10,
        "usual_end_hour": 24,
        "known_recipients": [
            {"id": "R401", "name": "AWS Cloud Services", "upi": "awsbill@paytm", "tx_count": 12, "regular_amount": 4250.0, "regular_time": "1st of Month"},
            {"id": "R402", "name": "WeWork Hyderabad", "upi": "wework@axis", "tx_count": 10, "regular_amount": 8500.0, "regular_time": "5th of Month"},
            {"id": "R403", "name": "Karan (UI Subcontractor)", "upi": "karan.dev@okhdfc", "tx_count": 9, "regular_amount": 15000.0, "regular_time": "End of Month"},
        ],
        "known_devices": ["DEV_ANANYA_MACBOOK_PRO", "DEV_ANANYA_ONEPLUS11"],
        "usual_regions": ["Hyderabad", "Bengaluru"],
        "transaction_count": 110,
        "profile_status": "ESTABLISHED",
        "trusted_patterns": [
            {"title": "Co-working Space", "category": "Workspace", "typical_amount": 8500.0, "frequency": "Monthly", "recipient_id": "R402"},
            {"title": "Adobe Creative Cloud", "category": "Software", "typical_amount": 4250.0, "frequency": "Monthly", "recipient_id": "R401"},
        ]
    }
}

SCENARIOS: Dict[str, Dict[str, Any]] = {
    "scenario_a": {
        "id": "scenario_a",
        "title": "Scenario A: Safe Everyday Payment",
        "tag": "Safe Payment",
        "user_id": "U102",
        "description": "₹850 grocery payment to Nature Basket during normal daytime hours from known iPhone.",
        "transaction": {
            "transaction_id": "TXN_DEMO_A",
            "user_id": "U102",
            "recipient_id": "R202",
            "recipient_name": "Nature Basket Groceries",
            "recipient_upi": "naturebasket@paytm",
            "amount": 850.0,
            "timestamp": "2026-08-21T11:30:00",
            "device_id": "DEV_VIKRAM_IPHONE15",
            "location_region": "Mumbai",
            "is_known_recipient": True,
            "is_known_device": True,
            "failed_attempts_recent": 0,
        },
        "expected_risk_band": "LOW",
        "expected_action": "ALLOW",
        "expected_score_range": [0, 20],
        "intent_context": {
            "category": "PURCHASE",
            "free_text": "Weekly groceries",
        }
    },
    "scenario_b": {
        "id": "scenario_b",
        "title": "Scenario B: Legitimate Monthly Rent (Same Amount, Safe Context)",
        "tag": "Legitimate Recurring",
        "user_id": "U102",
        "description": "₹50,000 monthly rent to known Landlord on 1st of month. High value, but matches established pattern.",
        "transaction": {
            "transaction_id": "TXN_DEMO_B",
            "user_id": "U102",
            "recipient_id": "R201",
            "recipient_name": "Suresh Nair (Landlord)",
            "recipient_upi": "suresh.nair@okhdfcbank",
            "amount": 50000.0,
            "timestamp": "2026-08-21T10:15:00",
            "device_id": "DEV_VIKRAM_IPHONE15",
            "location_region": "Mumbai",
            "is_known_recipient": True,
            "is_known_device": True,
            "failed_attempts_recent": 0,
        },
        "expected_risk_band": "LOW",
        "expected_action": "ALLOW",
        "expected_score_range": [0, 30],
        "intent_context": {
            "category": "RENT_BILL",
            "free_text": "Monthly house rent for flat 402",
        }
    },
    "scenario_c": {
        "id": "scenario_c",
        "title": "Scenario C: Suspicious Context (Same Amount, Risky Context)",
        "tag": "Suspicious Context",
        "user_id": "U102",
        "description": "₹45,000 to first-time recipient Amit Kumar at 2:07 AM from an unrecognized device.",
        "transaction": {
            "transaction_id": "TXN_DEMO_C",
            "user_id": "U102",
            "recipient_id": "R991",
            "recipient_name": "Amit Kumar",
            "recipient_upi": "amit.kumar89@okaxis",
            "amount": 45000.0,
            "timestamp": "2026-08-21T02:07:00",
            "device_id": "DEV_UNKNOWN_REDMI_12",
            "location_region": "Mumbai",
            "is_known_recipient": False,
            "is_known_device": False,
            "failed_attempts_recent": 0,
        },
        "expected_risk_band": "HIGH",
        "expected_action": "CONFIRM",
        "expected_score_range": [56, 79],
        "intent_context": {
            "category": "FAMILY_FRIEND",
            "free_text": "Urgent medical bill transfer for brother's hospital admission",
        }
    },
    "scenario_d": {
        "id": "scenario_d",
        "title": "Scenario D: High-Risk Coercion / ATO Simulation",
        "tag": "High Risk / Escalate",
        "user_id": "U102",
        "description": "₹75,000 to new recipient at 3:18 AM from new device with 2 recent failed attempts in an unusual location.",
        "transaction": {
            "transaction_id": "TXN_DEMO_D",
            "user_id": "U102",
            "recipient_id": "R999",
            "recipient_name": "QuickCrypto Pay",
            "recipient_upi": "fastcrypto@ybl",
            "amount": 75000.0,
            "timestamp": "2026-08-21T03:18:00",
            "device_id": "DEV_NEW_DEVICE_EMULATOR",
            "location_region": "Kolkata",
            "is_known_recipient": False,
            "is_known_device": False,
            "failed_attempts_recent": 2,
        },
        "expected_risk_band": "VERY_HIGH",
        "expected_action": "ESCALATE",
        "expected_score_range": [80, 100],
        "intent_context": {
            "category": "INVESTMENT",
            "free_text": "Transferring funds immediately as instructed over Telegram group call",
        }
    }
}
